### ISSUE TITLE
No build_atf.sh in optee/ATF/tools-images-hikey960

### ISSUE THREAD

**Issue by ChangMinPark-UB** [bsupiot/hikey960-aosp-optee#2]
Now, I got to **Build ARM-Trusted-Firmware** step on Wiki.

It says I need to goto directory **"optee/ATF/tools-images-hikey960"**.
However, there is no build file **"build_atf.sh"**.

"build_atf.sh" is located only in **"device/linaro/hikey960/"**.

So, I just ran the script above, but I'm still confused with below sentence in wiki.
> Next build can be started with $ ./build_atf.sh

Does it mean that I need to run the script two times? However after running the above script once, the script still remains not-executable file. 

Am I missing any pre-step before running this script?

**Comment by ZQQ1024** [comment]
Hi, you need to patch atf_script_patch.diff in directory "optee/ATF/tools-images-hikey960".

**Comment by ChangMinPark-UB** [comment]
Oh, I patched on different directory(device/linaro/hikey960/), and that was the issue. 
Thank you for quick response. 

Can you tell me exactly where I need to patch other two diff files?

I patched **_aosp_optee_patch.diff_** in **_device/linaro/hikey_** and **_optee_os_patch.diff_** in **_optee/optee_os/core/arch/arm/plat-hikey_**.

**Comment by ZQQ1024** [comment]
`optee/optee_os/core/arch/arm/plat-hikey` for `optee_os_patch.diff`
`device/linaro/hikey` for `aosp_optee_patch.diff`
`optee/ATF/tools-images-hikey960` for `atf_script_patch.diff`

I am not sure about the destination, but I got no problems up till now.

**Comment by ChangMinPark-UB** [comment]
Great, thanks!
