### ISSUE TITLE
xtest segmentation fault

### ISSUE THREAD

**Issue by ChangMinPark-UB** [bsupiot/hikey960-aosp-optee#3]
Hi,

Thanks a lot for the build settings on Hikey960 board.
However while building, I got an **xtest** error. 

I followed all the steps on Wiki and flashed Hikey960 board as the direction.
When it boots up, tee-supplicant wasn't running. 
So I ran,  (After this, checked whether it's running: **$ ps -A | grep tee-supplicant**)
`$ tee-supplicant &`
After that, I run xtest.
`$ xtest`

However, it gives Segmentation Fault error. The error is below. 

**regression_1001 Core self tests
external/optee_test/host/xtest/regression_1000.c:246: res has an unexpected value 0xffff000e = TEEC_ERROR_COMMUNICATION, expected 0x0 = TEEC_SUCCESS**

1) Do you know the solution for this test error?

2) Also when the board boots up normally, a monitor connected with the board does not show anything. It shows up when I flashed with regular AOSP on the board, but is this what it supposed to be after flashing with Optee+AOSP?

**Comment by bsupiot** [comment]
Hi @ChangMinPark,

> 1. Do you know the solution for this test error?

Sometimes I have the same behavior, restart tee-supplicant seems to "solve" this issue. However, the best xtest result I obtain is : 

```
16065 subtests of which 3 failed  
75 test cases of which 1 failed  
0 test case was skipped  
TEE test application done!
```

So, there is other type of errors. Can you run optee_example_hello_world without errors ? 

>2. Also when the board boots up normally, a monitor connected with the board does not show anything. It shows up when I flashed with regular AOSP on the board, but is this what it supposed to be after flashing with Optee+AOSP?

As for me my monitor show android boot and home. Do you plug your monitor before or after booting up ?.

**Comment by ChangMinPark-UB** [comment]
Thanks for the response.

> Sometimes I have the same behavior, restart tee-supplicant seems to "solve" this issue.

I killed, restarted, and run xtest again over ten times, but it still gives same error. 

> Can you run optee_example_hello_world without errors ?

It gives an error below.
`optee_example_hello_world: TEEC_Opensession failed with code 0xffff000e origin 0x2`

> Do you plug your monitor before or after booting up ?.

I always plug it before booting. I just tried plugging it after booting, and a monitor doesn't show anything still.

**Comment by bsupiot** [comment]
Hi @ChangMinPark,

Your board has 3 or 4 GB RAM ?

**Comment by ChangMinPark-UB** [comment]
My board has 3GB RAM.
And I configured `CFG_DRAM_SIZE_GB=3` in **_/plat-hikey/conf.mk_**.

**Comment by bsupiot** [comment]
Ok, it's the main difference but I don't understand why it can't works.

**Comment by ChangMinPark-UB** [comment]
Okay, I'm trying to figure out. 
Please let me know if you find any solution for this.

Thanks.

**Comment by ChangMinPark-UB** [comment]
One more question,

> For the first build use :
> `$ source build_atf.sh` or `$ . build_atf.sh`
> Next build can be started with `$ ./build_atf.sh`

On above direction, what do you mean by next build can be started with `$ ./build_atf.sh`?
Does it mean that I need to build twice with the same script?
Also even after first build, the file doesn't become executable.

**Comment by bsupiot** [comment]
>On above direction, what do you mean by next build can be started with $ ./build_atf.sh?

In the build script I initialize variables needed by other build script. So for the first build in a shell (if you reopen a shell it's consider as a first build) you need to use `source` or `.` in order to set environment variables. When environment variables are set you can use the script normally. 

>Does it mean that I need to build twice with the same script?

No need.

>Also even after first build, the file doesn't become executable.

If it's not executable add the executable right

**Comment by ChangMinPark-UB** [comment]
Okay, I think that's what I did exactly. 
Actually my board was 4GB, and it builds fine with 4GB configuration. 

Thank you so much for the help!
